version: 2
jobs:
  build:

    working_directory: ~/crow

    docker:
      - image: blacklabelops/swarm-jdk8

    steps:

      - checkout
      - setup_remote_docker

      #- restore_cache:
      #    key: circleci-crow-{{ checksum "pom.xml" }}

      - run: mvn clean install cobertura:cobertura

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-crow-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: console/target/surefire-reports

      - store_artifacts:
          path: application/target/crow-application-0.5-SNAPSHOT.jar

      - run: bash <(curl -s https://codecov.io/bash)
